### ISSUE TITLE
Missed tweets from filteredStream

### ISSUE THREAD

**Issue by simonbuehler** [redwebcreation/twitter-stream-api#14] opened 2022-08-01 09:07 UTC
hi,

i have some problems where some tweets don't get fetched when using the FilteredStream api, i have no exceptions but it feels like a conenction / delay issue as also sometimes a whole chunk of feeds comes in but delayed. Using a elevated token this shouldn't happen, any hint how to debug this?

**Comment by felixdorn** [comment] 2022-08-01 09:18
Are you missing some tweets completely or do they just come with a delay?

**Comment by simonbuehler** [comment] 2022-08-01 09:51
i experienced both behaviour actually , tried with https://github.com/PLhery/node-twitter-api-v2 to exclude some auth / serverside problems and its works instant with that package, is there a way to add some debugging to it like sending keepalive monitoring etc? a bit clueless here

**Comment by felixdorn** [comment] 2022-08-01 15:14
You can access the response from the Closure using $this->response.

-------- Original Message --------

**Comment by felixdorn** [comment] 2022-08-05 13:04
Closing as I can't reproduce. Will reopen if you provide more details.

**Closed by felixdorn** 2022-08-05 13:04 UTC
